name: Build and Release

on: 
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            zipname: OoTMM-ER-Plotter-Windows-x64.zip
          - os: ubuntu-latest
            zipname: OoTMM-ER-Plotter-Ubuntu-x64.zip
          - os: macos-latest
            zipname: OoTMM-ER-Plotter-Macos-arm64.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Create Build Contents
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.14.7'
          pyinstaller_ver: '==6.22.3'
          spec: 'main.spec'
          requirements: 'requirements.txt'

      - name: Upload Build
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.zipname }}
          path: ./dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Download builds
        uses: actions/download-artifact@v8
        with:
          pattern: OoTMM-ER-Plotter-*-*64.zip
          path: dist/
          skip-decompress: true
          merge-multiple: true
        
      - name: Display structure of downloaded files
        run: ls -R dist/
        
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          generate_release_notes: true
          files: |
            dist/OoTMM-ER-Plotter-*-*64.zip
